// Generated by typings
// Source: https://raw.githubusercontent.com/nozzlegear/dateformat.d.ts/master/dateformat.d.ts
declare module '~dateformat/dateformat' {
interface __DateFormat
{
    (date: Date, format: string): string;
    
    masks: {};
} 

var dateFormat: __DateFormat;

export = dateFormat;
}
declare module 'dateformat/dateformat' {
import main = require('~dateformat/dateformat');
export = main;
}
declare module 'dateformat' {
import main = require('~dateformat/dateformat');
export = main;
}
